const allCoinList = [
	{ id: 30, name: "Aave", apiName: "aave" },
	{ id: 71, name: "Algorand", apiName: "algorand" },
	{ id: 64, name: "Amp", apiName: "amp-token" },
	{ id: 23, name: "ApeCoin", apiName: "apecoin" },
	{ id: 54, name: "Arweave", apiName: "arweave" },
	{ id: 10, name: "Avalanche", apiName: "avalanche-2" },
	{ id: 26, name: "Axie Infinity", apiName: "axie-infinity" },
	{ id: 60, name: "Basic Attention Token", apiName: "basic-attention-token" },
	{ id: 3, name: "Binance Coin", apiName: "binancecoin" },
	{ id: 1, name: "Bitcoin", apiName: "bitcoin" },
	{ id: 20, name: "Bitcoin Cash", apiName: "bitcoin-cash" },
	{ id: 38, name: "Bitcoin SV", apiName: "bitcoin-cash-sv" },
	{ id: 55, name: "BitDAO", apiName: "bitdao" },
	{ id: 4, name: "Cardano", apiName: "cardano" },
	{ id: 72, name: "Chain Token", apiName: "chain-2" },
	{ id: 18, name: "Chainlink", apiName: "chainlink" },
	{ id: 62, name: "Celo", apiName: "celo" },
	{ id: 50, name: "Chiliz", apiName: "chiliz" },
	{ id: 66, name: "Convex Finance", apiName: "convex-finance" },
	{ id: 73, name: "Cosmos", apiName: "cosmos" },
	{ id: 13, name: "Cronos", apiName: "crypto-com-chain" },
	{ id: 69, name: "Curve DAO", apiName: "curve-dao-token" },
	{ id: 53, name: "Dash", apiName: "dash" },
	{ id: 29, name: "Decentraland", apiName: "decentraland" },
	{ id: 37, name: "DeFiChain", apiName: "defichain" },
	{ id: 7, name: "Dogecoin", apiName: "dogecoin" },
	{ id: 28, name: "Elrond", apiName: "elrond-erd-2" },
	{ id: 59, name: "Enjin Coin", apiName: "enjincoin" },
	{ id: 32, name: "EOS", apiName: "eos" },
	{ id: 2, name: "Ethereum", apiName: "ethereum" },
	{ id: 74, name: "Ethereum Classic", apiName: "ethereum-classic" },
	{ id: 42, name: "Fantom", apiName: "fantom" },
	{ id: 27, name: "Filecoin", apiName: "filecoin" },
	{ id: 70, name: "FLEX Coin", apiName: "flex-coin" },
	{ id: 75, name: "Flow", apiName: "flow" },
	{ id: 17, name: "FTX", apiName: "ftx-token" },
	{ id: 63, name: "Gala", apiName: "gala" },
	{ id: 47, name: "Gate", apiName: "gatechain-token" },
	{ id: 67, name: "Gnosis", apiName: "gnosis" },
	{ id: 33, name: "The Graph", apiName: "the-graph" },
	{ id: 68, name: "Harmony", apiName: "harmony" },
	{ id: 76, name: "Hedera", apiName: "hedera-hashgraph" },
	{ id: 40, name: "Helium", apiName: "helium" },
	{ id: 35, name: "Huobi Token", apiName: "huobi-token" },
	{ id: 41, name: "IOTA", apiName: "iota" },
	{ id: 24, name: "Internet Computer", apiName: "internet-computer" },
	{ id: 65, name: "Kava", apiName: "kava" },
	{ id: 36, name: "Klaytn", apiName: "klay-token" },
	{ id: 56, name: "Kusama", apiName: "kusama" },
	{ id: 12, name: "LEO Token", apiName: "leo-token" },
	{ id: 14, name: "Litecoin", apiName: "litecoin" },
	{ id: 52, name: "Loopring", apiName: "loopring" },
	{ id: 39, name: "Maker", apiName: "maker" },
	{ id: 77, name: "Monero", apiName: "monero" },
	{ id: 16, name: "Near", apiName: "near" },
	{ id: 45, name: "NEO", apiName: "neo" },
	{ id: 51, name: "NEXO", apiName: "nexo" },
	{ id: 78, name: "OKB", apiName: "okb" },
	{ id: 48, name: "PancakeSwap", apiName: "pancakeswap-token" },
	{ id: 8, name: "Polkadot", apiName: "polkadot" },
	{ id: 15, name: "Polygon", apiName: "matic-network" },
	{ id: 44, name: "Quant", apiName: "quant-network" },
	{ id: 25, name: "The Sandbox", apiName: "the-sandbox" },
	{ id: 11, name: "Shiba Inu", apiName: "shiba-inu" },
	{ id: 6, name: "Solana", apiName: "solana" },
	{ id: 61, name: "Stacks", apiName: "blockstack" },
	{ id: 19, name: "Stellar", apiName: "stellar" },
	{ id: 58, name: "STEPN", apiName: "stepn" },
	{ id: 57, name: "Synthetix Network", apiName: "havven" },
	{ id: 22, name: "Tezos", apiName: "tezos" },
	{ id: 21, name: "Theta Fuel", apiName: "theta-fuel" },
	{ id: 31, name: "Theta Network", apiName: "theta-token" },
	{ id: 43, name: "THORChain", apiName: "thorchain" },
	{ id: 9, name: "Tron", apiName: "tron" },
	{ id: 79, name: "Uniswap", apiName: "uniswap" },
	{ id: 80, name: "VeChain", apiName: "vechain" },
	{ id: 46, name: "Waves", apiName: "waves" },
	{ id: 5, name: "XRP", apiName: "ripple" },
	{ id: 34, name: "Zcash", apiName: "zcash" },
	{ id: 49, name: "Zilliqa", apiName: "zilliqa" },
];

export default allCoinList;

// currently to Flex, Coin #70 -- #80 coins so far
